runtime: python39
service: default
instance_class: F2
entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

env_variables:
  GOOGLE_API_KEY: "AIzaSyBQPPbYgiv1o56FakqrbS1p5LdpFJr9G-Y"
  FIREBASE_SERVICE_ACCOUNT_KEY_PATH: "./serviceAccountKey.json"

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

network:
  session_affinity: true 